#!/usr/bin/env sh

CONF_DIR=${XDG_CONFIG_HOME:-"$HOME/.config"}
export CONF_DIR

# Create ~/.config directory if it doesn't exist
mkdir -p "$CONF_DIR"
parent_dir=$(cd "$(dirname "$0")" && pwd -P)

for f in "$parent_dir"/*/; do
  name=$(basename "$f")
  if [ ! -e "$CONF_DIR/$name" ]; then
    ln -s "$f" "$CONF_DIR/$name"
  fi
done

if [ ! -e "$HOME/.gitconfig" ]; then
  ln -s "$parent_dir/.gitconfig" "$HOME/.gitconfig"
fi
