#!/bin/zsh

export CONF_DIR=$HOME/.config

# Create ~/.config directory if it doesn't exist
mkdir -p $CONF_DIR
local parent_dir=$(realpath $(dirname "$0"))
for f in "$parent_dir"/*/; do
  local name=$(basename $f)
  if [ ! -d $CONF_DIR/$name ]; then
    ln -s $f $CONF_DIR/$name
  fi
done

ln $parent_dir/zsh/.zshenv $HOME/.zshenv 2> /dev/null || :
ln $parent_dir/.gitconfig $HOME/.gitconfig 2> /dev/null || :
