[tools]
node = "latest"
python = "latest"
watchexec = "latest"

[settings]
experimental = true
status = { missing_tools = "if_other_versions_installed", show_env = true, show_tools = false }
minimum_release_age = "7d"
