#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# bar settings
yabai -m config status_bar off

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_placement second_child
yabai -m config window_topmost off

yabai -m config window_shadow on

yabai -m config window_opacity off
# yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 0.9

yabai -m config window_border off
# yabai -m config window_border_width 10

yabai -m config split_ratio 0.50
yabai -m config auto_balance on

yabai -m config mouse_modifier fn
yabai -m config mouse_action1 resize
yabai -m config mouse_action2 move

# general space settings
yabai -m config layout bsp

yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8

yabai -m rule --add app="^App Store" manage=off grid=4:4:1:1:2:2
yabai -m rule --add app="^System Settings$" manage=off grid=4:4:1:1:2:2
yabai -m rule --add app="^Install.?" manage=off grid=4:4:1:1:2:2
yabai -m rule --add app="Dashlane" manage=off grid=4:4:1:1:2:2
yabai -m rule --add app="Snap Camera" manage=off grid=4:4:1:1:2:2
yabai -m rule --add app="Zoom" manage=off grid=4:4:1:1:2:2
yabai -m rule --add app="^Adobe.*" manage=off

# sketchybar
yabai -m config external_bar all:40:0
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

borders active_color=0xffc8ffc3 inactive_color=0xffbbb8ff width=6.0 &

echo "yabai configuration loaded.."
