SPACESHIP_PROMPT_ORDER=(
  time
  user
  dir
  host
  git
  package
  venv
  battery
  line_sep
  vi_mode
)
SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_AMPM_SHOW=true
SPACESHIP_TIME_PM=" "
SPACESHIP_TIME_AM="  "
SPACESHIP_TIME_PREFIX=" "
SPACESHIP_TIME_12HR=true
SPACESHIP_TIME_FORMAT="%D{%-I:%M \033[34mon\033[0m %-m/%d }"
SPACESHIP_DIR_PREFIX="\033[34min\033[0m "
SPACESHIP_VI_MODE_INSERT="  "
SPACESHIP_VI_MODE_NORMAL="  "
SPACESHIP_VI_MODE_SUFFIX=""
SPACESHIP_VI_MODE_COLOR="red"
SPACESHIP_GIT_STATUS_COLOR="yellow"
SPACESHIP_GIT_STATUS_PREFIX=" "
SPACESHIP_GIT_STATUS_SUFFIX=" "
SPACESHIP_GIT_STATUS_UNTRACKED=""
SPACESHIP_GIT_STATUS_ADDED=" "
SPACESHIP_GIT_STATUS_MODIFIED=""
SPACESHIP_GIT_STATUS_RENAMED=" "
SPACESHIP_GIT_STATUS_DELETED=""
SPACESHIP_GIT_STATUS_STASHED=""
SPACESHIP_GIT_STATUS_UNMERGED=""
SPACESHIP_GIT_STATUS_AHEAD=""
SPACESHIP_GIT_STATUS_BEHIND=""
SPACESHIP_GIT_STATUS_DIVERGED=""
SPACESHIP_NODE_SYMBOL="⬢ "
SPACESHIP_RUBY_SYMBOL=" "
SPACESHIP_VENV_SYMBOL=" "
SPACESHIP_VENV_PREFIX=""
SPACESHIP_VENV_COLOR="red"
