[tool.poetry]
name = "poetry-instance"
version = "1.8.2"
description = ""
authors = []
license = ""

[tool.poetry.dependencies]
python = "3.12.2"
poetry = "^1.8.2"

[tool.poetry.group.additional.dependencies]
poetry-dotenv-plugin = "^0.2.0"
poetry-plugin-export = "^1.6.0"

