[tool.poetry]
name = "poetry-instance"
version = "1.8.4"
description = ""
authors = []
license = ""
package-mode = false

[tool.poetry.dependencies]
python = "3.13.0"
poetry = "1.8.4"

[tool.poetry.group.additional.dependencies]
poetry-dotenv-plugin = "^0.2.0"
poetry-plugin-export = "^1.6.0"

